#
# Serverless configuration of HTTP endpoints
#

service: basicapi

provider:
  name: aws
  runtime: nodejs8.10

functions:
  getCompanyList:
    handler: build_out/handler.handler1
    events:
      - http: 
          path: /companies
          method: get
          request: 
          parameters: 
             paths: 
               id: true
    environment:
      SLS_DEBUG: true