#
# Serverless configuration for a generic endpoint
#

service: basicapi

provider:
  name: aws
  runtime: nodejs8.10

functions:
  any:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline
  - serverless-plugin-typescript

package:
  exclude:
    - node_modules/**/*
  include:
    index.ts
