service: basicapi

provider:
  name: aws
  runtime: nodejs8.10

functions:
  getCompanyList:
    handler: build_out/handler.getCompanyList
    events:
      - http: 
          path: /companies
          method: get
          request: 
          parameters: 
             paths: 
               id: true
    environment:
      SLS_DEBUG: true

  getCompanyTransactions:
    handler: build_out/handler.getCompanyTransactions
    events:
      - http: 
          path: /companies/{id}/transactions
          method: get
          request: 
          parameters: 
             paths: 
               id: true
    environment:
      SLS_DEBUG: true      