#
# Serverless configuration for a generic endpoint
#

service: basicapi

provider:
  name: aws
  runtime: nodejs8.10

functions:
  any:
    handler: aws.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

package:
  artifact:
    .build/deploy.zip