service: basicapi

provider:
  name: aws
  runtime: nodejs8.10

functions:
  getCompanyList:
    handler: build/handler.getCompanyList
    events:
      - http: 
          path: /companies
          method: get
    environment:
      SLS_DEBUG: true

  getCompanyTransactions:
    handler: build/handler.getCompanyTransactions
    events:
      - http: 
          path: /companies/{id}/transactions
          method: get
          request: 
          parameters: 
             paths: 
               id: true
    environment:
      SLS_DEBUG: true

package:
  exclude:
  - src/**
  - test/**
  - package*.json
  - ts*.json
include:
  - build/handler.js
