service: basicapi

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2
  profile: default

functions:
  getUserClaims:
    handler: build/handler.getUserClaims
    events:
      - http: 
          path: /userclaims/current
          method: get
          cors:
            origin: 'http://serverless.spa.com.s3-website.eu-west-2.amazonaws.com'

  getCompanyList:
    handler: build/handler.getCompanyList
    events:
      - http: 
          path: /companies
          method: get
          cors:
            origin: 'http://serverless.spa.com.s3-website.eu-west-2.amazonaws.com'

  getCompanyTransactions:
    handler: build/handler.getCompanyTransactions
    events:
      - http: 
          path: /companies/{id}/transactions
          method: get
          cors:
            origin: 'http://serverless.spa.com.s3-website.eu-west-2.amazonaws.com'
          request: 
            parameters: 
              paths: 
                id: true

# Include non development dependencies only so that the upload size is small - see below links:
#   https://github.com/serverless/serverless/issues/569
#   https://gist.github.com/ugnb/0ca7d9ac5c3efe4171d0f33e48a34189#file-serverless-yml
#
# On Windows download the zip and unzip tools from these URLs:
#   http://gnuwin32.sourceforge.net/packages/zip.htm
#   http://gnuwin32.sourceforge.net/packages/unzip.htm
#
# Do I need to use these EXEs on Windows?
#   http://stahlworks.com/dev/index.php?tool=zipunzip
custom:
  scripts:
    hooks:

      'after:package:createDeploymentArtifacts': >
        (cd .serverless && unzip -qq basicapi.zip -d basicapi && cd ..) &&
        (cd .serverless/basicapi && npm install --only=prod > /dev/null 2>&1  && cd .. && cd ..) &&
        (cd .serverless/basicapi && zip -q -FSr ../basicapi.zip . && cd .. && cd ..)

# Include only transpiled Javascript in the package
# Node modules are excluded here and managed via the above hook instead
package:
  exclude:
  - node_modules/**/*
  - src/**
  - test/**
  - ts*.json
  include:
  - build/handler.js

plugins:
  - serverless-plugin-scripts